instrumentation:
  root: .
  default-excludes: true
  excludes:
    - karma.conf.js
    - gulpfile.*
    - Gulpfile.*
    - Gruntfile.*
    - gruntfile.*
    - examples/**/*.js
    - dist/**/*.js
  include-all-sources: true
