language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
before_install:
- npm install -g grunt-cli
before_script:
- grunt demo > demo_output &
script:
- grunt jshint
- grunt lint5
- grunt style
- ./travis.sh
after_script:
- cat demo_output
