language: node_js
node_js:
- lts/*
- node
env:
- MOZ_HEADLESS=1
- TEST=cover
matrix:
  include:
  - node_js: node
    env: TEST="browser-cover -- --browsers chrome,firefox"
sudo: false
addons:
    chrome: stable
    firefox: latest
before_deploy:
- npm install -g npm
deploy:
  provider: npm
  email: alex@layton.in
  api_key:
    secure: MSF2Ok2kfWmgPhMX1uB0PUYmlYQqW6fRXllVaRsC7lZJ5EBpqK/mGgzCreqX9jHHY7TlVk7kaHHgP8SCnkILEDNgeEhy0+KX+P8eKAm5PD4AUjnSbKa0bilBrIz+k66cM54furE5amPf+F6s1B6K0q6v3WkHZuiFEL8rHEfIpKY=
  on:
    node: node
    tags: true
    all_branches: true
    repo: OADA/oada-id-client-js
before_install:
- npm install -g coveralls
script:
- npm run $TEST
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
