language: node_js
node_js:
- '0.10'
addons:
  sauce_connect:
    username: awlayton_github
    access_key:
      secure: E3SYptoju8MEcOg0vK/Jtvyau1/jdXPAnxxHRSwqOWTVZlugazNLlFNlQxSM0jppEHtg2r4zYcFKB7jAx+UOF7goeRhilZrv17iYU8T/SbTSJwh08AFp6n7PgQxvnrKFJqwb9xu6k4+4NS/52B8Wu66+LdXYOVSuAzaL6pbLCnQ=
before_install:
- npm install -g grunt-cli
script:
- ./travis.sh
env:
  global:
  - secure: M3AbvYX/wuwcW73n/VtTD0gC64FhkiqYBR8yab1NbwWUbVZwM6VcjAt3YrXsCQwC7VLMkgcd4cG0WW/M9qvdeWfHSWT3N7wW/KHCFDV7kWEeN4EZndKUSvdyv/DiHxvjUym5H63GXNOQKFGvdw0UgNYASpwZf8pbaUW5/FjGA1c=
  - secure: UokrTVglxqge/3xIGMpRmPO1GTL+I8Bou4SewC3Ta9nad6ByUcpZp2hw/XbJPo47/YPdXCWVJGuJ2PGf//XVYCWYwrv7cXtUU/FI/JZiaZCB1Fxwvqcd9PFfUJ/zEO26Xr9k0vGh8X21jrzZ/iQN4fmoIz+My3ZB5nkbdnU/yEM=
