language: node_js
node_js:
- '0.10'
addons:
  sauce_connect:
    username:
      secure: Fcj3wx0+uUEuz3GfGLlTpTBwdDxWZiqnAw8PlLx15Txp2y+0u9a5eI8axVT/mMCtbT0s3AkSXArr0Lb7ZzxbwMys4PcZZyTWG245ov15H/bsD3dl8Ep+MXqZAdAJtMLLphoNFta8KD8w9iaB1Yen7bQQKOphoL3yRdOVZxRZB/0=
    access_key:
      secure: Bqfv13ktmnHhBK6/9oHLFObg9FFuRnMTmEHkaE2EDRG+8DH0M/tDNBUkmYUMUTAmbWIFmUhu6IRdG4weO/57lNS8Ja22rUPghOKJ311fp7wRNPhDhasA78M+FD1wYwsSw7SX7NSxo9dom9hHsIaYEW8oR7rQC4EgpZjtu1ure7U=
before_install:
- npm install -g grunt-cli
before_script:
- grunt demo &
script:
- ./travis.sh
